-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Sep 27, 2016 at 11:14 PM
-- Server version: 10.1.16-MariaDB
-- PHP Version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `hackathon_2016`
--

-- --------------------------------------------------------

--
-- Table structure for table `etms_data_pack`
--

CREATE TABLE `etms_data_pack` (
  `id` int(10) UNSIGNED NOT NULL,
  `NumOfXRefs` varchar(12) DEFAULT NULL,
  `ReferOutCount` varchar(12) DEFAULT NULL,
  `TransferCount` varchar(12) DEFAULT NULL,
  `ManualActCount` varchar(12) DEFAULT NULL,
  `AutomationCount` varchar(4) DEFAULT NULL,
  `TotalTime` int(6) DEFAULT NULL,
  `CreateByWG` varchar(20) DEFAULT NULL,
  `LastTMG` varchar(19) DEFAULT NULL,
  `LastTOG` varchar(8) DEFAULT NULL,
  `ResolveByWG` varchar(20) DEFAULT NULL,
  `MTTRView` varchar(10) DEFAULT NULL,
  `ReportSource` varchar(8) DEFAULT NULL,
  `ReceivedVia` varchar(8) DEFAULT NULL,
  `SourceSystem` varchar(18) DEFAULT NULL,
  `PubToCust` varchar(18) DEFAULT NULL,
  `FAIFlag` varchar(1) DEFAULT NULL,
  `Domain` varchar(5) DEFAULT NULL,
  `Severity` varchar(8) DEFAULT NULL,
  `Priority` varchar(5) DEFAULT NULL,
  `PriorityChange` varchar(13) DEFAULT NULL,
  `TicketType` varchar(10) DEFAULT NULL,
  `ProductType` varchar(10) DEFAULT NULL,
  `ProductFamily` varchar(7) DEFAULT NULL,
  `Product` varchar(9) DEFAULT NULL,
  `CountryCode` varchar(5) DEFAULT NULL,
  `IntPubFlag` varchar(1) DEFAULT NULL,
  `AlertCusFlag` int(1) DEFAULT NULL,
  `SymptomCode` varchar(9) DEFAULT NULL,
  `ResolutionPlatform` varchar(8) DEFAULT NULL,
  `NoTouchFlag` int(1) DEFAULT NULL,
  `HANKFlag` int(1) DEFAULT NULL,
  `L3StabilityMonitoringProcess` int(1) DEFAULT NULL,
  `CompleteD1NBCPE` int(1) DEFAULT NULL,
  `AutoResolveProcess` int(1) DEFAULT NULL,
  `TidyTicketProcess` int(1) DEFAULT NULL,
  `ChildResolveProcess` int(1) DEFAULT NULL,
  `ScheduleChildResolveProcess` int(1) DEFAULT NULL,
  `PlannedMaintenanceProcess` int(1) DEFAULT NULL,
  `L1ALARMEXIST` varchar(5) DEFAULT NULL,
  `CustServiceFlag` int(1) DEFAULT NULL,
  `RepairCenterFlag` int(1) DEFAULT NULL,
  `NetworkWGFlag` int(1) DEFAULT NULL,
  `FieldOpsWGFlag` varchar(5) DEFAULT NULL,
  `lecWGFlag` int(1) DEFAULT NULL,
  `OtherWGFlag` int(1) DEFAULT NULL,
  `SLAMTTR` varchar(5) DEFAULT NULL,
  `Exception` int(1) DEFAULT NULL,
  `CriticalIndicator` varchar(5) DEFAULT NULL,
  `E2EiSvcFlag` int(1) DEFAULT NULL,
  `ITILType` varchar(5) DEFAULT NULL,
  `nB_prediction` int(1) DEFAULT NULL,
  `XG_Prediction` int(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `etms_data_pack`
--

INSERT INTO `etms_data_pack` (`id`, `NumOfXRefs`, `ReferOutCount`, `TransferCount`, `ManualActCount`, `AutomationCount`, `TotalTime`, `CreateByWG`, `LastTMG`, `LastTOG`, `ResolveByWG`, `MTTRView`, `ReportSource`, `ReceivedVia`, `SourceSystem`, `PubToCust`, `FAIFlag`, `Domain`, `Severity`, `Priority`, `PriorityChange`, `TicketType`, `ProductType`, `ProductFamily`, `Product`, `CountryCode`, `IntPubFlag`, `AlertCusFlag`, `SymptomCode`, `ResolutionPlatform`, `NoTouchFlag`, `HANKFlag`, `L3StabilityMonitoringProcess`, `CompleteD1NBCPE`, `AutoResolveProcess`, `TidyTicketProcess`, `ChildResolveProcess`, `ScheduleChildResolveProcess`, `PlannedMaintenanceProcess`, `L1ALARMEXIST`, `CustServiceFlag`, `RepairCenterFlag`, `NetworkWGFlag`, `FieldOpsWGFlag`, `lecWGFlag`, `OtherWGFlag`, `SLAMTTR`, `Exception`, `CriticalIndicator`, `E2EiSvcFlag`, `ITILType`, `nB_prediction`, `XG_Prediction`) VALUES
(1, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 7343, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'Other', 'N/A', '4', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 0, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(2, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 17133, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Network', 'Transport', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 1, 'N', 0, 'I', 0, 0),
(3, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4178, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(4, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 18, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(5, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 18, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(6, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 100, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Network', 'Transport', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(7, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 67055, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, 'Other', 0, 'N', 0, 'I', 0, 0),
(8, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 52, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '480', 0, 'N', 0, 'I', 0, 0),
(9, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 4699, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 1, 1),
(10, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(11, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 56, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(12, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 1, 1),
(13, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1578, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(14, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4290, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(15, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 7194, 'PROACTIVE.AUTOMATION', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'IP', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'Other', 'IP', 'Other', 'Other', 'Y', 0, 'DOWN HARD', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '240', 0, 'N', 0, 'I', 0, 0),
(16, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 30903, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'VOICE', 'Other', '3', 'Downgraded', 'CUSTROUBLE', 'CIRCUIT', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, 'Other', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(17, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1057, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(18, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 10, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', '2', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(19, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 44246, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 0, 0, '7200', 1, 'N', 0, 'I', 0, 0),
(20, 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8470, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 1, 0, '300', 0, 'N', 0, 'I', 0, 0),
(21, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 7, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(22, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4836, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, 'Other', 0, 'N', 0, 'I', 0, 0),
(23, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 32, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(24, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 6, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(25, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(26, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9108, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(27, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 51, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(28, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4881, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(29, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 15, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(30, 'Zero', 'Zero', 'MoreThanZero', 'Zero', 'Zero', 4764, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(31, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 5007, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(32, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4333, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Portals', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'DOWN HARD', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(33, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 103, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(34, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9625, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '480', 0, 'N', 0, 'I', 0, 0),
(35, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 51, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(36, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 51, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(37, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8415, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(38, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 2615, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(39, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 14, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '240', 0, 'N', 0, 'I', 0, 0),
(40, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 12203, 'Other', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '7200', 1, 'N', 0, 'I', 0, 0),
(41, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 198, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '4320', 0, 'N', 0, 'I', 0, 0),
(42, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 7, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(43, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4361, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(44, 'Zero', 'Zero', 'MoreThanZero', 'Zero', 'Zero', 4691, 'Other', 'MNSO.SMS', 'MNSO.SMS', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'ALL', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(45, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 20, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(46, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 7, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(47, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 635, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(48, 'Zero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 4915, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 1, 1, '300', 0, 'N', 0, 'I', 0, 0),
(49, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 4683, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'ALL', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(50, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 11523, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(51, 'MoreThanZero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 14321, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'ETMS GUI', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 1, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(52, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 227, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'N', 1, 'Other', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '7200', 0, 'N', 0, 'I', 1, 1),
(53, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4746, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'Other', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(54, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 1, 1),
(55, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 9, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(56, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 63, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Impact', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '480', 0, 'N', 0, 'I', 0, 0),
(57, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9243, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '480', 1, 'N', 0, 'I', 0, 0),
(58, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4387, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'DOWN HARD', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(59, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(60, 'Zero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 10220, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 1, 'N', 0, 'I', 0, 0),
(61, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 12, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(62, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 6316, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'None', 'N', 'Other', 'N/A', '2', 'Downgraded', 'Other', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(63, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9931, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(64, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9757, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '480', 0, 'N', 0, 'I', 0, 0),
(65, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4626, 'VBESGENERIC', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Other', 'Other', 'Other', 'C', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '240', 1, 'N', 1, 'I', 0, 0),
(66, 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 5095, 'PROACTIVE.AUTOMATION', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'Y', 0, 'DOWN HARD', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(67, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 50, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(68, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4366, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 1, 'N', 0, 'I', 0, 0),
(69, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 44006, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Impact', 'None', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'CUSTROUBLE', 'CIRCUIT', 'Data', 'Other', 'Other', 'C', 0, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(70, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4457, 'VBESGENERIC', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'Customer E-bonding', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(71, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8061, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(72, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1109, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 0, 0),
(73, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 35, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', '2', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(74, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4591, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Network', 'Transport', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(75, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 232, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'N', 1, 'Other', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '7200', 0, 'N', 0, 'I', 1, 1),
(76, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 4706, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(77, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 4738, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(78, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8203, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(79, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 6087, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(80, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 1454, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(81, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 5549, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '1440', 0, 'Other', 0, 'I', 0, 0),
(82, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(83, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 10053, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 0, 0),
(84, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 19006, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'N/A', '2', 'Other', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(85, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 14255, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(86, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4787, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(87, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 5418, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, 'Other', 0, 'N', 0, 'I', 0, 0),
(88, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 183, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(89, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4816, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(90, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 36, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'N', 1, 'Other', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'Other', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 1, 1),
(91, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 107, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(92, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 7985, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '4', 'Downgraded', 'Other', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 0, 0),
(93, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 24399, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(94, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 25, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 1, 1),
(95, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1300, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(96, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 62, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(97, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8188, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Network', 'Transport', 'Other', 'C', 0, 'DOWN HARD', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 1, 0, '300', 0, 'N', 1, 'I', 0, 0),
(98, 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 'Zero', 14395, 'PROACTIVE.AUTOMATION', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'Y', 0, 'DOWN HARD', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 1, 1),
(99, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 11226, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(100, 'MoreThanZero', 'Zero', 'Zero', 'Zero', 'Zero', 26, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 1, 'Other', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(101, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 8890, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 0, 0),
(102, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(103, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 16761, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 0, 0),
(104, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(105, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 10078, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'DATA', 'N/A', '3', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Other', 'Other', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(106, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 11226, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(107, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4821, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'None', 'N', 'Other', 'N/A', '2', 'Downgraded', 'Other', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(108, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4387, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'CUSTROUBLE', 'Other', 'Network', 'Transport', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '7200', 0, 'N', 0, 'I', 0, 0),
(109, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4423, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Network', 'Transport', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 1, 'N', 0, 'I', 0, 0),
(110, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 5919, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Network', 'Transport', 'Other', 'C', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '1440', 0, 'N', 1, 'I', 0, 0),
(111, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8456, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'None', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'CUSTROUBLE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'C', 0, 'DOWN HARD', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(112, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 16921, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'DOWN HARD', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(113, 'MoreThanZero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 4109, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'Other', 'Other', 'Other', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 1, 0, '240', 1, 'N', 0, 'I', 0, 0),
(114, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 257, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Impact', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '480', 0, 'N', 0, 'I', 0, 0),
(115, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 5834, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'Other', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '240', 0, 'N', 0, 'I', 0, 0),
(116, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 46, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(117, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 100, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(118, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1039, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'None', 'N', 'Other', 'OUTAGE', '4', 'Downgraded', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'C', 0, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(119, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 4750, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(120, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 21657, 'VBESGENERIC', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'Customer E-bonding', 'N', 'DATA', 'DEGRADED', '4', 'Downgraded', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 1, 0, '7200', 1, 'N', 0, 'I', 0, 0),
(121, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 3244, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'ETMS GUI', 'Customer E-bonding', 'N', 'DATA', 'DEGRADED', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 1, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 0, 0),
(122, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 5998, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 0, 0),
(123, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1542, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(124, 'Zero', 'Zero', 'MoreThanZero', 'Zero', 'Zero', 14401, 'PROACTIVE.AUTOMATION', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'CIRCUIT', 'Network', 'Transport', 'Other', 'Y', 0, 'DOWN HARD', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 1, 1),
(125, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 25975, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '480', 1, 'N', 0, 'I', 0, 0),
(126, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 8982, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(127, 'Zero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 4609, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(128, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 51, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(129, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 12546, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'Other', 'SVCMANAGED', 'Network', 'Transport', 'Other', 'Y', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 1, 0, '300', 1, 'N', 0, 'I', 0, 0),
(130, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 5825, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Impact', 'Portals', 'N', 'DATA', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Data', 'Other', 'Other', 'C', 0, 'Other', 'CNO', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, 'Other', 1, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(131, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 3445, 'Other', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 0, 0),
(132, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 3072, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(133, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 9486, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '7200', 0, 'N', 0, 'I', 0, 0),
(134, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4696, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 1, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(135, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 34023, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(136, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 2, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'ETMS GUI', 'None', 'N', 'Other', 'N/A', '4', 'No net change', 'Other', 'Other', 'Other', 'Other', 'Other', 'Y', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'Other', 0, 0);
INSERT INTO `etms_data_pack` (`id`, `NumOfXRefs`, `ReferOutCount`, `TransferCount`, `ManualActCount`, `AutomationCount`, `TotalTime`, `CreateByWG`, `LastTMG`, `LastTOG`, `ResolveByWG`, `MTTRView`, `ReportSource`, `ReceivedVia`, `SourceSystem`, `PubToCust`, `FAIFlag`, `Domain`, `Severity`, `Priority`, `PriorityChange`, `TicketType`, `ProductType`, `ProductFamily`, `Product`, `CountryCode`, `IntPubFlag`, `AlertCusFlag`, `SymptomCode`, `ResolutionPlatform`, `NoTouchFlag`, `HANKFlag`, `L3StabilityMonitoringProcess`, `CompleteD1NBCPE`, `AutoResolveProcess`, `TidyTicketProcess`, `ChildResolveProcess`, `ScheduleChildResolveProcess`, `PlannedMaintenanceProcess`, `L1ALARMEXIST`, `CustServiceFlag`, `RepairCenterFlag`, `NetworkWGFlag`, `FieldOpsWGFlag`, `lecWGFlag`, `OtherWGFlag`, `SLAMTTR`, `Exception`, `CriticalIndicator`, `E2EiSvcFlag`, `ITILType`, `nB_prediction`, `XG_Prediction`) VALUES
(137, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 250147, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '7200', 1, 'N', 0, 'I', 0, 0),
(138, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(139, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1175, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(140, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1294, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Other', 'None', 'N', 'IP', 'Other', '4', 'No net change', 'Other', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(141, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 249745, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'N/A', '4', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 1, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '7200', 1, 'N', 0, 'I', 0, 0),
(142, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 36, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'N', 0, 'Other', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'Other', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 1, 1),
(143, 'Zero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 5507, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(144, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 2499, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 0, 0),
(145, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 5679, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'Other', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(146, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 152162, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'Other', 'Impact', 'Portals', 'N', 'Other', 'N/A', '4', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'C', 1, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '4320', 1, 'N', 0, 'I', 0, 0),
(147, 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4409, 'Other', 'INCIDENT.MANAGEMENT', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'DOWN HARD', 'CNO', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 1, 0, '300', 0, 'N', 0, 'I', 0, 0),
(148, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 69, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(149, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9694, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 1, 0, '300', 0, 'N', 0, 'I', 0, 0),
(150, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8686, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(151, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9441, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '480', 0, 'N', 0, 'I', 0, 0),
(152, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4679, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'Portals', 'N', 'Other', 'N/A', '3', 'No net change', 'CUSTROUBLE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(153, 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 8594, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'DOWN HARD', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 1, 0, '300', 1, 'N', 0, 'I', 0, 0),
(154, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9512, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 1, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, 'Other', 0, 'N', 0, 'I', 0, 0),
(155, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 5, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(156, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4591, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Network', 'Transport', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(157, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 751, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 1, 'Other', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(158, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 5696, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(159, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 19, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 1, 1),
(160, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1060, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'Other', 'Impact', 'Customer E-bonding', 'N', 'Other', 'N/A', '4', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'C', 1, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '4320', 0, 'N', 0, 'I', 0, 0),
(161, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 18423, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(162, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 1502, 'VBESGENERIC', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Network', 'Transport', 'Other', 'C', 0, 'Other', 'CNO', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, '300', 0, 'N', 1, 'I', 0, 0),
(163, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4348, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(164, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 50, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 1, 1),
(165, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 11, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'DATA', 'Other', 'Other', 'No net change', 'Other', 'CIRCUIT', 'Data', 'Other', 'Other', 'N', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '240', 0, 'N', 0, 'I', 0, 0),
(166, 'Zero', 'Zero', 'MoreThanZero', 'Zero', 'Zero', 1498, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'IP', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'ALARM GEN', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 1, 1),
(167, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 6053, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(168, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 76, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'DATA', 'N/A', '4', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'N', 0, 'Other', 'Other', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 1, 1),
(169, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 50, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'Other', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 1, 1),
(170, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 41, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Impact', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'Other', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(171, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 3719, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'Other', 'Impact', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'Other', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(172, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 1071, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'Other', 'N/A', '4', 'No net change', 'CUSTROUBLE', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '1440', 0, 'N', 0, 'I', 0, 0),
(173, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 2843, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(174, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 7247, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'None', 'N', 'Other', 'N/A', '2', 'Downgraded', 'Other', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(175, 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 9015, 'Other', 'INCIDENT.MANAGEMENT', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'Other', 'Portals', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'C', 0, 'DOWN HARD', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 1, 1, '300', 1, 'N', 0, 'I', 0, 0),
(176, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 113411, 'TRIAGE.SMS', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'None', 'N', 'Other', 'DEGRADED', '4', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Data', 'Other', 'Other', 'N', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 1, '0', 0, 0, '1440', 1, 'N', 0, 'I', 0, 0),
(177, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 10024, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'CUSTROUBLE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'C', 1, 'DOWN HARD', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(178, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 11360, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Other', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 0, 0),
(179, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 6602, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(180, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 5987, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(181, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 18433, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 1, 'I', 0, 0),
(182, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 21310, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'PHONE', 'ETMS GUI', 'None', 'N', 'Other', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'C', 0, 'Other', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 0, '0', 0, 0, '480', 1, 'N', 0, 'I', 0, 0),
(183, 'MoreThanZero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4591, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'Network', 'Transport', 'Other', 'Y', 0, 'ROUTER', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(184, 'Zero', 'Zero', 'Zero', 'Zero', 'Zero', 49, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '2', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '1440', 0, 'N', 0, 'I', 1, 1),
(185, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 14589, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(186, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 19634, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'ALARM', 'Impact', 'None', 'N', 'IP', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'Other', 'IP', 'Other', 'Other', 'Y', 0, 'DOWN HARD', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(187, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 12178, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'Other', 0, 'I', 0, 0),
(188, 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 'Zero', 1460, 'PROACTIVE.AUTOMATION', 'Other', 'Other', 'PROACTIVE.AUTOMATION', 'NonMSCust', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'CIRCUIT', 'IP', 'PIP', 'Other', 'Y', 0, 'DOWN HARD', 'CNO', 1, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '240', 0, 'N', 0, 'I', 1, 1),
(189, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 13859, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'QUICKTKT', 'Portals', 'None', 'N', 'VOICE', 'DEGRADED', '2', 'No net change', 'CUSTROUBLE', 'Other', 'Other', 'Other', 'Other', 'N', 0, 'Other', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(190, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 6222, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'IP', 'OUTAGE', '4', 'Downgraded', 'CUSTROUBLE', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'ALARM GEN', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 0, 0, '7200', 0, 'N', 0, 'I', 0, 0),
(191, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 2226, 'TRIAGE.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MNSO.SMS', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '300', 0, 'N', 0, 'I', 0, 0),
(192, 'Zero', 'MoreThanZero', 'MoreThanZero', 'MoreThanZero', 'Zero', 6429, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 0, 1, '0', 1, 0, '300', 0, 'N', 0, 'I', 0, 0),
(193, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 4912, 'VBESGENERIC', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '2', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Other', 'Other', 'Other', 'C', 0, 'Other', 'CNO', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 1, 0, '0', 0, 1, '1440', 0, 'N', 1, 'I', 0, 0),
(194, 'MoreThanZero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 6187, 'VBESGENERIC', 'Other', 'Other', 'Other', 'NonMSCust', 'CUSTOMER', 'WEB SVC', 'Customer E-bonding', 'Customer E-bonding', 'N', 'DATA', 'DEGRADED', '3', 'No net change', 'CUSTROUBLE', 'CIRCUIT', 'Network', 'Transport', 'Other', 'C', 0, 'Other', 'CNO', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, 'Other', 0, 'N', 1, 'I', 0, 0),
(195, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 5019, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'IPVPN', 'Other', 'Y', 1, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(196, 'MoreThanZero', 'MoreThanZero', 'Zero', 'MoreThanZero', 'Zero', 20815, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '1', 'No net change', 'PROACTIVE', 'SVCMANAGED', 'IP', 'PIP', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0),
(197, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 10054, 'TRIAGE.EMS2', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Customer E-bonding', 'N', 'Other', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'MGD NTWK', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 0, '0', 0, 1, '480', 0, 'N', 0, 'I', 0, 0),
(198, 'Zero', 'Zero', 'Zero', 'MoreThanZero', 'Zero', 4399, 'Other', 'Other', 'Other', 'Other', 'MSCustomer', 'INTERNAL', 'IAM', 'Impact', 'Portals', 'N', 'DATA', 'OUTAGE', '3', 'Downgraded', 'PROACTIVE', 'SVCMANAGED', 'IP', 'Other', 'Other', 'Y', 0, 'ROUTER', 'ALL', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 0, 0, 1, '0', 0, 0, 'Other', 0, 'N', 0, 'I', 0, 0),
(199, 'Zero', 'Zero', 'MoreThanZero', 'MoreThanZero', 'Zero', 1545, 'Other', 'Other', 'Other', 'Other', 'NonMSCust', 'INTERNAL', 'Other', 'Impact', 'None', 'N', 'IP', 'OUTAGE', '1', 'No net change', 'CUSTROUBLE', 'Other', 'IP', 'Other', 'Other', 'N', 0, 'ALARM GEN', 'Other', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 1, 1, '0', 0, 0, '300', 0, 'N', 0, 'I', 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id_user` int(10) UNSIGNED NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id_user`, `username`, `password`, `email`) VALUES
(1, 'arun', 'arun', 'arun@verizon.com');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `etms_data_pack`
--
ALTER TABLE `etms_data_pack`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id_user`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `etms_data_pack`
--
ALTER TABLE `etms_data_pack`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=200;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id_user` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
